export const IPC = {
  accountsList: 'accounts:list',
  accountsSave: 'accounts:save',
  accountsDelete: 'accounts:delete',
  accountsTest: 'accounts:test',
  mailboxes: 'mail:mailboxes',
  messages: 'mail:messages',
  message: 'mail:message',
  markSeen: 'mail:markSeen',
  markAllSeen: 'mail:markAllSeen',
  flag: 'mail:flag',
  deleteMessage: 'mail:delete',
  moveMessage: 'mail:move',
  saveAttachment: 'mail:saveAttachment',
  attachmentData: 'mail:attachmentData',
  send: 'mail:send',
  sync: 'mail:sync',
  search: 'mail:search',
  unified: 'mail:unified',
  saveDraft: 'mail:saveDraft',
  openExternal: 'app:openExternal',
  appVersion: 'app:version',
  // App-Einstellungen
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  oauthStart: 'oauth:start',
  oauthConfigGet: 'oauth:configGet',
  oauthConfigSet: 'oauth:configSet',
  oauthImportGoogle: 'oauth:importGoogle',
  // Wegwerf-Postfach (mail.tm)
  tempList: 'temp:list',
  tempCreate: 'temp:create',
  tempRemove: 'temp:remove',
  tempActivate: 'temp:activate',
  tempMessages: 'temp:messages',
  tempMessage: 'temp:message',
  tempMarkAllSeen: 'temp:markAllSeen',
  tempSaveAttachment: 'temp:saveAttachment',
  // Auto-Update
  updateCheck: 'update:check',
  updateApply: 'update:apply',
  // Fenstersteuerung (eigene Titelleiste)
  winMinimize: 'win:minimize',
  winMaximizeToggle: 'win:maximizeToggle',
  winClose: 'win:close',
  // main -> renderer events
  onStatus: 'evt:status',
  onNewMail: 'evt:newMail',
  onUpdate: 'evt:update'
} as const
